name: Update CloudWatch Rules List

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy hàng ngày lúc 00:00 UTC
  workflow_dispatch:  # Cho phép chạy thủ công

env:
  AWS_REGION: ap-southeast-1  # Thay bằng region của bạn

permissions:
  contents: read
  id-token: write  # Cần cho OIDC authentication
  actions: write   # Cần để lưu artifact

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Get CloudWatch Event Rules
        id: get-rules
        run: |
          echo "Fetching CloudWatch Event Rules..."
          RULES=$(aws events list-rules --query 'Rules[*].Name' --output json | jq -r '.[]' | jq -R . | jq -s .)
          echo "{\"rules\":$RULES}" > rules.json
          echo "Found rules: $RULES"

      - name: Upload Rules List as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudwatch-rules
          path: rules.json
          retention-days: 1