name: "Check AWS Logs"

on:
  workflow_dispatch:  # Cho phép chạy workflow thủ công

jobs:
  check-aws-logs:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-1  # Thay thế nếu cần region khác
      LOG_GROUP_NAME: "/aws/lambda/test-S3-lambda-first"
      SEARCH_STRING: "ERROR"  # Chuỗi cần tìm trong logs
      LIMIT: 5  # Số lượng record muốn lấy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Kiểm tra biến môi trường trong GitHub Actions
      - name: Debug Environment Variables
        run: env

      # Kiểm tra xem AWS Region có được thiết lập đúng không
      - name: Check AWS Region
        run: echo "AWS Region is $AWS_REGION"

      # Kiểm tra AWS credentials có hoạt động không
      - name: Verify AWS Authentication
        run: aws sts get-caller-identity

      # Kiểm tra danh sách log groups trong AWS CloudWatch
      - name: List Log Groups
        run: aws logs describe-log-groups --region $AWS_REGION

      # Truy vấn logs từ CloudWatch Logs với bộ lọc ERROR
      - name: Fetch CloudWatch Logs
        run: |
          aws logs filter-log-events \
            --log-group-name "$LOG_GROUP_NAME" \
            --limit "$LIMIT" \
            --filter-pattern "$SEARCH_STRING" \
            --region "$AWS_REGION"
