name: "Check AWS Logs"

on:
  workflow_dispatch:

jobs:
  check-aws-logs:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "ap-southeast-1"
      LOG_GROUP_NAME: "/aws/lambda/test-S3-lambda-first"
      SEARCH_STRING: "INIT_START"
      LIMIT: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-1"  # ✅ Truyền giá trị trực tiếp

      - name: Verify AWS Authentication
        run: aws sts get-caller-identity

      - name: List Log Groups
        run: aws logs describe-log-groups --region "ap-southeast-1"

      - name: Fetch CloudWatch Logs
        run: |
          aws logs filter-log-events \
            --log-group-name "$LOG_GROUP_NAME" \
            --limit "$LIMIT" \
            --filter-pattern "$SEARCH_STRING" \
            --region "ap-southeast-1"
