name: Fetch CloudWatch Error Logs

on:
  workflow_dispatch:
    inputs:
      max_items:
        description: 'Số lượng items tối đa trả về'
        required: true
        default: '10'
      search_string:
        description: 'Chuỗi cần tìm trong @message'
        required: true

jobs:
  fetch-cloudwatch-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Fetch CloudWatch Logs
        run: |
          LOG_GROUP_NAME="/aws/lambda/test-S3-lambda-first"
          SEARCH_STRING="${{ github.event.inputs.search_string }}"
          MAX_ITEMS="${{ github.event.inputs.max_items }}"

          QUERY="fields @timestamp, @message | filter level =~ /ERROR|error/ and @message like '${SEARCH_STRING}' | sort @timestamp desc | limit ${MAX_ITEMS}"

          QUERY_ID=$(aws logs start-query --log-group-name "$LOG_GROUP_NAME" --query-string "$QUERY" --start-time $(date -d '5 minutes ago' +%s) --end-time $(date +%s) --query 'queryId' --output text)

          echo "Đợi kết quả truy vấn..."
          sleep 5
          
          # Lấy kết quả truy vấn, đảm bảo lấy đúng JSON format
          RESULTS_JSON=$(aws logs get-query-results --query-id "$QUERY_ID")

          # Xử lý dữ liệu trả về, chỉ lấy giá trị logs để tránh lỗi format
          LOG_RESULTS=$(echo "$RESULTS_JSON" | jq -c '.results')

          echo "Dữ liệu logs đã lấy được:"
          echo "$LOG_RESULTS"

          # Xuất biến ENV để dùng trong bước tiếp theo
          echo "LOG_RESULTS=$LOG_RESULTS" >> $GITHUB_ENV

      - name: Use log data
        run: |
          echo "Kết quả logs đã xử lý:"
          echo "$LOG_RESULTS"
