name: Fetch CloudWatch Error Logs

on:
  workflow_dispatch:
    inputs:
      max_items:
        description: 'Số lượng items tối đa trả về'
        required: true
        default: '10'
      search_string:
        description: 'Chuỗi cần tìm trong @message'
        required: true
      start_time:
        description: 'Thời gian bắt đầu (YYYY-MM-DD HH:MM:SS UTC)'
        required: true
      end_time:
        description: 'Thời gian kết thúc (YYYY-MM-DD HH:MM:SS UTC)'
        required: true

jobs:
  fetch-cloudwatch-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Debug environment variables
        run: env
      - name: Check AWS Region
        run: echo "AWS Region is $AWS_REGION"
      - name: Test AWS CLI
        run: aws sts get-caller-identity
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Convert Start Time and End Time to Epoch
        run: |
          START_TIME="${{ github.event.inputs.start_time }}"
          END_TIME="${{ github.event.inputs.end_time }}"

          if [[ -z "$START_TIME" || -z "$END_TIME" ]]; then
            echo "❌ ERROR: start_time hoặc end_time không được để trống!"
            exit 1
          fi

          START_EPOCH=$(date -u --date="$START_TIME" +%s 2>/dev/null || echo "")
          END_EPOCH=$(date -u --date="$END_TIME" +%s 2>/dev/null || echo "")

          if [[ -z "$START_EPOCH" || -z "$END_EPOCH" ]]; then
            echo "❌ ERROR: start_time hoặc end_time không hợp lệ! Vui lòng nhập đúng format YYYY-MM-DD HH:MM:SS UTC"
            exit 1
          fi

          echo "START_EPOCH=$START_EPOCH" >> $GITHUB_ENV
          echo "END_EPOCH=$END_EPOCH" >> $GITHUB_ENV

      - name: Fetch CloudWatch Logs
        run: |
          LOG_GROUP_NAME="/aws/lambda/test-S3-lambda-first"
          SEARCH_STRING="${{ github.event.inputs.search_string }}"
          MAX_ITEMS="${{ github.event.inputs.max_items }}"

          ESCAPED_SEARCH_STRING=$(echo "$SEARCH_STRING" | sed 's/"/\\"/g')

          QUERY="fields @timestamp, @message | filter level =~ /ERROR|error/ and @message like \"${ESCAPED_SEARCH_STRING}\" | sort @timestamp desc | limit ${MAX_ITEMS}"

          QUERY_ID=$(aws logs start-query --log-group-name "$LOG_GROUP_NAME" --query-string "$QUERY" --start-time "$START_EPOCH" --end-time "$END_EPOCH" --query 'queryId' --output text)

          echo "Đợi kết quả truy vấn..."
          sleep 5

          # Chờ truy vấn hoàn thành (tối đa 60 giây)
          for i in {1..12}; do
            QUERY_STATUS=$(aws logs get-query-results --query-id "$QUERY_ID" --query 'status' --output text)
            echo "Query status: $QUERY_STATUS"
            if [[ "$QUERY_STATUS" == "Complete" ]]; then
              break
            fi
            sleep 5
          done

          RESULTS_JSON=$(aws logs get-query-results --query-id "$QUERY_ID")

          LOG_RESULTS=$(echo "$RESULTS_JSON" | jq -c '.results')

          echo "Dữ liệu logs đã lấy được:"
          echo "$LOG_RESULTS"

          echo "LOG_RESULTS=$LOG_RESULTS" >> $GITHUB_ENV

      - name: Use log data
        run: |
          echo "Kết quả logs đã xử lý:"
          echo "$LOG_RESULTS"
