name: Send Slack Notification

on:
  workflow_call:
    inputs:
      color:
        required: true
        type: string
      message:
        required: true
        type: string
      title:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: true

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Decode Base64 message
        run: |
          echo "DECODED_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "${{ inputs.message }}" | base64 -d >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Confirm Data before Send Slack
        run: |
          echo "Decoded Message:"
          echo "${{ env.DECODED_MESSAGE }}"

      - name: Send message to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ inputs.color }}
          SLACK_TITLE: ${{ inputs.title }}
          #${{ env.DECODED_MESSAGE }}
          SLACK_MESSAGE: |
            *${{ inputs.title }}*
            ```json
            $(echo "${{ inputs.message }}" | base64 -d)
            ```

