name: Update EventBridge Scheduler List

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy hàng ngày lúc 00:00 UTC
  workflow_dispatch:   # Cho phép chạy thủ công

env:
  AWS_REGION: ap-southeast-1  # Thay bằng region của bạn

permissions:
  contents: read
  id-token: write    # Cần cho OIDC authentication
  actions: write     # Cần để lưu artifact

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # BƯỚC MỚI: Cập nhật AWS CLI lên phiên bản mới nhất
      # Lý do: Lỗi "Unknown options: --schedule-group-name" thường do AWS CLI quá cũ
      - name: Update AWS CLI to latest version
        run: |
          echo "Updating AWS CLI to the latest version..."
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
          echo "AWS CLI updated."

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }} # Sử dụng biến môi trường AWS_REGION

      - name: Verify AWS Identity
        run: |
          echo "Verifying AWS Caller Identity..."
          aws sts get-caller-identity
          echo "AWS Identity verified successfully. If the above command failed, check your AWS credentials and permissions."

      - name: Get EventBridge Scheduler Schedules
        id: get-rules
        run: |
          echo "Fetching EventBridge Scheduler Schedules..."
          
          # Lệnh AWS CLI gốc để lấy tên các lịch trình
          # Sử dụng biến môi trường AWS_REGION
          AWS_CLI_OUTPUT=$(aws scheduler list-schedules --schedule-group-name default --query 'Schedules[*].Name' --output json --region ${{ env.AWS_REGION }})
          
          echo "Raw AWS CLI output for schedules: $AWS_CLI_OUTPUT"
          
          # BƯỚC MỚI: Lưu output thô vào file để debug
          echo "$AWS_CLI_OUTPUT" > raw_rules_output.json
          
          # BƯỚC MỚI: Đơn giản hóa lệnh jq để tạo JSON cuối cùng
          # Đảm bảo rằng $AWS_CLI_OUTPUT là một mảng JSON hợp lệ (ví dụ: ["schedule1", "schedule2"] hoặc [])
          # Nếu $AWS_CLI_OUTPUT rỗng hoặc không hợp lệ, jq -n --argjson sẽ xử lý nó một cách an toàn.
          FINAL_JSON=$(jq -n --argjson rules "$AWS_CLI_OUTPUT" '{"rules": $rules}')
          
          echo "$FINAL_JSON" > rules.json
          echo "Generated rules.json content:"
          cat rules.json # In nội dung file cuối cùng ra log
          
          # In danh sách các lịch trình được tìm thấy (nếu có)
          echo "Found schedules: $(echo "$FINAL_JSON" | jq -r '.rules[]' | tr '\n' ' ')"

      - name: Upload Raw Schedules List as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: raw-scheduler-schedules-output
          path: raw_rules_output.json
          retention-days: 1 # Giữ artifact này trong 1 ngày

      - name: Upload Processed Schedules List as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scheduler-schedules
          path: rules.json
          retention-days: 1 # Giữ artifact này trong 1 ngày